#!/usr/bin/env bash

function main {
    case $BLOCK_BUTTON in
        1) zenity --info --width=600 --text="$(acpi -b)\n$(acpi -a)" &>/dev/null & ;;
    esac

    printf "%s" "⚡"
    acpi -b | IFS="," awk 'BEGIN { FS = "," } ; { print $2 }' | tr -d '[:space:]'
    printf "%s\n" ""
}

main
