#!/usr/bin/env python3
from subprocess import run, PIPE

def main():
    print('🖥️ ', end='')

    network_cards_info = [(card, get_network_card_ip(card)) for card in get_current_network_cards()]
    parts = ['<span color="gray">' + i[0] + ':</span>' + i[1] for i in network_cards_info]

    print(' '.join(parts))

def get_network_card_ip(card):
    lines = cmd('ip', 'addr', 'show', card)
    inet_line = filter_lines_starting_with('inet ', lines)[0]

    return inet_line.split(' ')[1].split('/')[0]

def get_current_network_cards():
    routes = cmd('ip', 'route')
    default_routes = filter_lines_starting_with('default', routes)

    return [route.split(' ')[4] for route in default_routes]

def filter_lines_starting_with(prefix, lines):
    return list(filter(lambda line: line.startswith(prefix), lines))

def cmd(*args):
    return [line.strip() for line in run(args, stdout=PIPE, text=True).stdout.splitlines()]

main()
